# Generated by Django 4.0.4 on 2022-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('dateOfBirth', models.CharField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=10)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
